#    _____ __ __  _____ ______    ___  ___ ___  ____  ____   _____   ___
#   / ___/|  |  |/ ___/|      |  /  _]|   |   ||    ||    \ |     | /   \
#  (   \_ |  |  (   \_ |      | /  [_ | _   _ | |  | |  _  ||   __||     |
#   \__  ||  ~  |\__  ||_|  |_||    _]|  \_/  | |  | |  |  ||  |_  |  O  |
#   /  \ ||___, |/  \ |  |  |  |   [_ |   |   | |  | |  |  ||   _] |     |
#   \    ||     |\    |  |  |  |     ||   |   | |  | |  |  ||  |   |     |
#    \___||____/  \___|  |__|  |_____||___|___||____||__|__||__|    \___/
#
# SystemInfo
# © CMarco 2024
#
messages:
  color-scheme: 'GREEN'   # Please refer to Minecraft color codes
                          # (AQUA, YELLOW, RED, LIGHT_PURPLE, GREEN, . . .)

speedtest:
  update-frequency: 2500  # This allows you to set up how often you will receive
                          # a notification during the /speedtest command.
                          # The value is expressed in MILLISECONDS (s⋅1000)