name: "SystemInfo"
version: ${project.version}
main: "top.cmarco.systeminfo.plugin.SystemInfo"
authors: ["CMarco"]
softdepend: ["PlaceholderAPI"]
description: "SystemInfo - The Master of Server Hardware."
