name: "SystemInfo"
version: ${project.version}
main: studio.thevipershow.systeminfo.SystemInfo
api-version: '1.20'
load: STARTUP
authors: [TheViperShow]
softdepend: [PlaceholderAPI]
description: "An amazing plugin to monitor your hardware and server stats"
libraries:
  - 'com.github.oshi:oshi-core:6.4.6'
