name: "SystemInfo"
version: ${project.version}
main: top.cmarco.systeminfo.plugin.SystemInfo
authors: [CMarco_]
softdepend: [PlaceholderAPI]
description: "An amazing plugin to monitor your hardware and server stats"
